### ISSUE TITLE
Elastic search 1.7.1 fails when i use http basic with Transport client.

### ISSUE THREAD

**Issue by naveenann** [Asquera/elasticsearch-http-basic#58]
Hello,

I am trying to use the transport client with http basic auth. Will it support to use both node client and Transport client?
```
 Settings s = null;
        try {
            s = ImmutableSettings.settingsBuilder().put("path.data", DATA_DIRECTORY)
                    .put("script.disable_dynamic", false)
                    .loadFromUrl(fl.toURI().toURL()).build();

        } catch (SettingsException e1) {
            e1.printStackTrace();
        } catch (MalformedURLException e1) {
            e1.printStackTrace();
        }
        node = NodeBuilder.nodeBuilder().data(true).settings(s).node()
                .start();
        client = node.client();
        node.start();
        new TransportClient(s).addTransportAddress(new InetSocketTransportAddress("127.0.0.1", 9300));
```

I get this error 
```
Exception in thread "main" org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) No implementation for org.elasticsearch.discovery.Discovery was bound.
  while locating org.elasticsearch.discovery.Discovery
    for parameter 3 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 4 at org.elasticsearch.http.HttpServer.<init>(Unknown Source)
  at _unknown_

2) No implementation for org.elasticsearch.discovery.Discovery was bound.
  while locating org.elasticsearch.discovery.Discovery
    for parameter 3 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 4 at com.asquera.elasticsearch.plugins.http.HttpBasicServer.<init>(Unknown Source)
  at _unknown_

3) No implementation for org.elasticsearch.indices.IndicesLifecycle was bound.
  while locating org.elasticsearch.indices.IndicesLifecycle
    for parameter 1 at org.elasticsearch.indices.IndicesService.<init>(Unknown Source)
  while locating org.elasticsearch.indices.IndicesService
    for parameter 5 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 4 at org.elasticsearch.http.HttpServer.<init>(Unknown Source)
  at _unknown_

4) No implementation for org.elasticsearch.indices.IndicesLifecycle was bound.
  while locating org.elasticsearch.indices.IndicesLifecycle
    for parameter 1 at org.elasticsearch.indices.IndicesService.<init>(Unknown Source)
  while locating org.elasticsearch.indices.IndicesService
    for parameter 5 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 4 at com.asquera.elasticsearch.plugins.http.HttpBasicServer.<init>(Unknown Source)
  at _unknown_

5) No implementation for org.elasticsearch.monitor.fs.FsProbe was bound.
  while locating org.elasticsearch.monitor.fs.FsProbe
    for parameter 1 at org.elasticsearch.monitor.fs.FsService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.fs.FsService
    for parameter 6 at org.elasticsearch.monitor.MonitorService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.MonitorService
    for parameter 2 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 4 at org.elasticsearch.http.HttpServer.<init>(Unknown Source)
  at _unknown_

6) No implementation for org.elasticsearch.monitor.fs.FsProbe was bound.
  while locating org.elasticsearch.monitor.fs.FsProbe
    for parameter 1 at org.elasticsearch.monitor.fs.FsService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.fs.FsService
    for parameter 6 at org.elasticsearch.monitor.MonitorService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.MonitorService
    for parameter 2 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 4 at com.asquera.elasticsearch.plugins.http.HttpBasicServer.<init>(Unknown Source)
  at _unknown_

7) No implementation for org.elasticsearch.monitor.network.NetworkProbe was bound.
  while locating org.elasticsearch.monitor.network.NetworkProbe
    for parameter 1 at org.elasticsearch.monitor.network.NetworkService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.network.NetworkService
    for parameter 5 at org.elasticsearch.monitor.MonitorService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.MonitorService
    for parameter 2 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 4 at org.elasticsearch.http.HttpServer.<init>(Unknown Source)
  at _unknown_

8) No implementation for org.elasticsearch.monitor.network.NetworkProbe was bound.
  while locating org.elasticsearch.monitor.network.NetworkProbe
    for parameter 1 at org.elasticsearch.monitor.network.NetworkService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.network.NetworkService
    for parameter 5 at org.elasticsearch.monitor.MonitorService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.MonitorService
    for parameter 2 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 4 at com.asquera.elasticsearch.plugins.http.HttpBasicServer.<init>(Unknown Source)
  at _unknown_

9) No implementation for org.elasticsearch.monitor.os.OsProbe was bound.
  while locating org.elasticsearch.monitor.os.OsProbe
    for parameter 1 at org.elasticsearch.monitor.os.OsService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.os.OsService
    for parameter 2 at org.elasticsearch.monitor.MonitorService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.MonitorService
    for parameter 2 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 4 at org.elasticsearch.http.HttpServer.<init>(Unknown Source)
  at _unknown_

10) No implementation for org.elasticsearch.monitor.os.OsProbe was bound.
  while locating org.elasticsearch.monitor.os.OsProbe
    for parameter 1 at org.elasticsearch.monitor.os.OsService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.os.OsService
    for parameter 2 at org.elasticsearch.monitor.MonitorService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.MonitorService
    for parameter 2 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 4 at com.asquera.elasticsearch.plugins.http.HttpBasicServer.<init>(Unknown Source)
  at _unknown_

11) No implementation for org.elasticsearch.monitor.process.ProcessProbe was bound.
  while locating org.elasticsearch.monitor.process.ProcessProbe
    for parameter 1 at org.elasticsearch.monitor.process.ProcessService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.process.ProcessService
    for parameter 3 at org.elasticsearch.monitor.MonitorService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.MonitorService
    for parameter 2 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 4 at org.elasticsearch.http.HttpServer.<init>(Unknown Source)
  at _unknown_

12) No implementation for org.elasticsearch.monitor.process.ProcessProbe was bound.
  while locating org.elasticsearch.monitor.process.ProcessProbe
    for parameter 1 at org.elasticsearch.monitor.process.ProcessService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.process.ProcessService
    for parameter 3 at org.elasticsearch.monitor.MonitorService.<init>(Unknown Source)
  while locating org.elasticsearch.monitor.MonitorService
    for parameter 2 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 4 at com.asquera.elasticsearch.plugins.http.HttpBasicServer.<init>(Unknown Source)
  at _unknown_

12 errors
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
	at org.elasticsearch.common.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:151)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:102)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:195)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:125)
	at com.searchblox.App.main(App.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by emig** [comment]
hi @naveenann  I just added some test that show that the plugin is compatible with the `TransportClient`. Please note that the plugin won't provide authentication to the `TransportClient`, since this uses an internal elasticsearch `transport` protocol and not `http`
